name: Snyk SCA Scan

on: [push]

permissions:
  contents: read

jobs:
  trufflehog:
    permissions:
      contents: read 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: trufflehogscanning
      id: scan
      continue-on-error: false
      run: |
       docker run -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --max-depth 10 --only-verified --fail
